#pragma once

#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define USB_MAX_POWER_CONSUMPTION 100
#define ONESHOT_TAP_TOGGLE        2
#define ONESHOT_TIMEOUT           3000
#define PERMISSIVE_HOLD_PER_KEY
#define QUICK_TAP_TERM_PER_KEY
#define TAPPING_TERM              200
#define BACKLIGHT_BREATHING
#define DYNAMIC_MACRO_NO_NESTING
#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD

#define MOUSEKEY_INTERVAL         20
#define MOUSEKEY_DELAY            0
#ifndef MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX      40
#endif
#define MOUSEKEY_MAX_SPEED        7
#ifndef MOUSEKEY_WHEEL_DELAY
#define MOUSEKEY_WHEEL_DELAY      0
#endif

#define ENABLE_RGB_MATRIX_DIGITAL_RAIN
